"team_name": "tafrika" # Your team name
"eval_method": ["mcqa","rag"] # mcqa, reward, rag, compression
"task_type": "causal_lm" # causal_lm, seq2seq
"policy_model_path": "tafrika/poly42_dpo" # Your path to the final checkpoint
"reference_model_path": "microsoft/Phi-3-mini-4k-instruct" # The repo id of your pretrained reference model
"quantized_policy_model_path": "./checkpoints/best_model_quantized/" # Your path to the final quantized checkpoint
"rag_policy_model_path": "tafrika/poly42_dpo" # Your path to the final RAG checkpoint
"test_data_path": "datasets/small_mmlu.jsonl" # Your path to the test data
"dpo_model_args":  # Put any model arguments required to load your DPO model below
  "trust_remote_code": True
"rag_model_args": # Put any model arguments required to load your rag model below
  "trust_remote_code": True
  "index_path": "documents/storage_lecture_notes" # or null for no RAG
"quantized_model_args": null # Put any model arguments required to load your quantized model below